### PR TITLE
New branch with Simplified and Traditional Chinese translations.

### PR DESCRIPTION
**Pull request by kentydotcom**
Following reviewer's suggestions 
(https://github.com/hyperledger/sawtooth-docs/pull/84#issuecomment-764981821), 
a new branch named "translation" was created to permit a separate PR for translations.  

Subfolder structure was followed from reviewer's suggestion
(https://github.com/kurtsson/jekyll-multiple-languages-plugin#42-folder-structure)
and implemented for Chinese (zh), which was subdivided for Simplified (Hans) and Traditional (Hant).  ISO codes were followed
(https://www.w3schools.com/tags/ref_language_codes.asp).

The faq.md file has been translated into Hans and Hant.  It may be used as a placeholder for internationalization of the FAQ folder.

### CODE REVIEW

**Comment by jsmitchell** [comment]
Don't add copyright lines for files you have not substantially modified (it looks like many of these files have just moved). For files where you are adding a copyright line, please conform with the existing pattern.

**Comment by jsmitchell** [comment]
Can you provide instructions for testing this change? Should we be able to see a generated site which contains a language selector?

**Comment by jsmitchell** [comment]
Does this PR supersede #84 ?

**Comment by dplumb94** [comment]
Thanks for the contribution! 

I noticed one of your commit messages is pretty long. In this repo we are following the Chris Beams standard for messages: https://chris.beams.io/posts/git-commit/#seven-rules. Please update the subject to 50 characters and add additional info in the body part of the commit message.

**Comment by vaporos** [comment]
I think we need to add the jekyll plugin code here so that it will automatically serve up the right translated content. Basically the pieces within https://github.com/kurtsson/jekyll-multiple-languages-plugin beyond just the folder structure.

**Comment by vaporos** [comment]
The translation work is desirable and good, but the site has recently undergone an overhaul and this will need reworking in order to match the current site.

**Pull request closed without merging**
