### PR TITLE
Update users.yml

### PR DESCRIPTION
**Pull request by mmsidani**
Bloxiom is a user.

### CODE REVIEW

**Comment by mmsidani** [comment]
Signed-off-by: Majed Sidani <mmsidani@gmail.com>

**Comment by mmsidani** [comment]
Signed-off-by: Majed Sidani <mmsidani@gmail.com>

**Comment by mmsidani** [comment]
Signed-off-by: Majed Sidani <mmsidani@gmail.com>

**Comment by peterschwarz** [comment]
I think you are missing the sign-offs in your commit message.  You can fix it by running

```
$ git commit -s --amend
```

While you are there, feel free to add some more description to your message, following this guide for writing commit messages: https://chris.beams.io/posts/git-commit/

After you've done this, force push your branch.

**Comment by mmsidani** [comment]
Thanks. I closed the request and I’ll resubmit. Thanks for the link.

**Pull request closed without merging**
