### PR TITLE
Update Docs index with release 1.1.3 link

### PR DESCRIPTION
**Pull request by Sutrannu**
Signed-off-by: Sutrannu <bbetts@bitwise.io>

### CODE REVIEW

**Comment by Sutrannu** [comment]
1.1.3 docs are [here](https://build.sawtooth.me/job/Sawtooth-Hyperledger/job/sawtooth-website/view/change-requests/job/PR-32/lastSuccessfulBuild/artifact/generator/archive/htdocs/docs/core/releases/1.1.3/) in Jenkins.

**Review by danintel — APPROVED** [review]
I assume the "Latest Release" link change will be automatic or is a separate process.

**Review by annechenette — APPROVED** [review]
The docs in the build artifacts look good (are the right version). I verified that they contain changes from every backported-to-1.1.3 doc PR.

**Comment by Sutrannu** [comment]
> I assume the "Latest Release" link change will be automatic or is a separate process.

@danintel, yes. The "latest" url path is handled by a symlink that gets updated when we archive a new version of the docs.

**Pull request merged**
