### PR TITLE
Refresh cleanup

### PR DESCRIPTION
**Pull request by rbuysse**

### CODE REVIEW

**Review by danintel — APPROVED** [review]
So is branch `master` renamed `refresh`?
Or is branch `refresh` some new branch, say for staging the website?

**Comment by rbuysse** [comment]
@danintel The latter! `refresh` is a feature branch for redesigning the website and simplifying the deployment process. We have the initial groundwork completed and will soon start converting the existing docs from .rst to markdown. Once the docs are converted, we'll merge `refresh` into` master`.

**Comment by danintel** [comment]
@rybuysse Thanks for the background info on refresh. Any reason for the work converting .rst to .md? Both convert to HTML.

**Comment by rbuysse** [comment]
We have some other docs repos (https://github.com/cargill/splinter-docs and https://github.com/hyperledger/grid-docs) using Jekyll for generation and it's been working real well.

**Review by vaporos — APPROVED** [review]

**Pull request merged**
